version: '2'
services:
  microservice:
    build: .
    image: zhanat87/golang-reactjs-redux:1.0.0
    environment:
      - PORT=8080
    ports:
      - "8080"
  # https://github.com/variadico/hellodocker
  proxy:
      image: nginx:latest
      ports:
          - "80:80" # host:container
          - "443:443"
      volumes:
          - ./nginx.conf:/etc/nginx/nginx.conf:ro
          # connect host's ./nginx.conf with container's nginx.conf
          # :ro == read only perms in container
      links:
          - microservice:app # [other container]:[alias in this container]
            # creates environment variables in proxy container
            # with ip and port info for go container
            # also creates entries in /etc/hosts with ip info
